[package]
name = "meshview"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.20.0"
eframe = "0.29.1"
egui = "0.29.1"
itertools = "0.14.0"
nalgebra = "0.33.2"
rand = "0.8.5"
rfd = "0.15.1"
tobj = "4.0.2"

[[bin]]
name = "your_app"
path = "src/main.rs"
windows_subsystem = "windows"
